create table UserActivity
(
    activityTime timestamp(6),
    id           number(19) generated by default as identity,
    username     varchar2(255) not null,
    primary key (id)
);

create table UserProfile
(
    id       number(19) generated by default as identity,
    fullName varchar2(255) not null,
    username varchar2(255) not null unique,
    primary key (id)
);

alter table UserActivity
    add constraint FKgw8obbdc2yw43lhaj8qequb4e
    foreign key (username)
    references UserProfile (username);
