################################################################
# TEST SETUP
# This is only present to allow testing against multiple RDBMS.
# Normal applications would use much simpler configuration.
# See https://quarkus.io/guides/hibernate-orm#persistence-unit-active
################################################################

# PostgreSQL configuration
quarkus.datasource."postgresql".db-kind=postgresql
quarkus.hibernate-orm."postgresql".packages=org.acme
quarkus.hibernate-orm."postgresql".datasource=postgresql
quarkus.flyway."postgresql".clean-at-start=true
quarkus.flyway."postgresql".migrate-at-start=true
quarkus.flyway."postgresql".locations=db/migration/postgresql

# Oracle configuration
quarkus.datasource."oracle".db-kind=oracle
quarkus.hibernate-orm."oracle".packages=org.acme
quarkus.hibernate-orm."oracle".datasource=oracle
quarkus.flyway."oracle".clean-at-start=true
quarkus.flyway."oracle".migrate-at-start=true
quarkus.flyway."oracle".locations=db/migration/oracle

# SQL Server configuration
quarkus.datasource."mssql".db-kind=mssql
quarkus.hibernate-orm."mssql".packages=org.acme
quarkus.hibernate-orm."mssql".datasource=mssql
quarkus.flyway."mssql".clean-at-start=true
quarkus.flyway."mssql".migrate-at-start=true
quarkus.flyway."mssql".locations=db/migration/mssql

# Profile-based activation

quarkus.datasource."postgresql".active=false
quarkus.hibernate-orm."postgresql".active=false
%postgresql.quarkus.datasource."postgresql".active=true
%postgresql.quarkus.hibernate-orm."postgresql".active=true

quarkus.datasource."oracle".active=false
quarkus.hibernate-orm."oracle".active=false
%oracle.quarkus.datasource."oracle".active=true
%oracle.quarkus.hibernate-orm."oracle".active=true

quarkus.datasource."mssql".active=false
quarkus.hibernate-orm."mssql".active=false
%mssql.quarkus.datasource."mssql".active=true
%mssql.quarkus.hibernate-orm."mssql".active=true

# IDE defaults
quarkus.test.profile=test,postgresql
