create table UserActivity
(
    activityTime timestamp(6),
    id           bigint generated by default as identity,
    username     varchar(255) not null,
    primary key (id)
);

create table UserProfile
(
    id       bigint generated by default as identity,
    fullName varchar(255) not null,
    username varchar(255) not null unique,
    primary key (id)
);

alter table if exists UserActivity
    add constraint FKgw8obbdc2yw43lhaj8qequb4e
    foreign key (username)
    references UserProfile (username);
